### ISSUE TITLE
Icon changes depending on which file is highlighted

### ISSUE THREAD

**Issue by ashtonsix** [file-icons/atom#638] opened 2017-08-13 03:57 UTC
In version `2.1.10`:

![recording](https://user-images.githubusercontent.com/6740947/29246019-b182bbc8-7fe3-11e7-89a6-8e7267863cc8.gif)

**Comment by Alhadis** [comment] 2017-08-13 04:11
Ah-hah, *finally!* A duplicate of #511 that I've been waiting for, because I've been meaning to get to the bottom of this elusive issue...

Alrighty. First thing's first: I need you to open the dev-tools up (**View menu** -> **Developer** -> **Toggle Developer Tools**), and open the contents of an item that keeps changing. Select the `<span>` tag directly inside the `<li>` element, and right-click and add a breakpoint (illustrated below):

<img src="https://user-images.githubusercontent.com/2346707/29246073-f0b929f6-8030-11e7-8836-0eb7ab80d58c.png" width="600" alt="Figure 1" />

This will pause execution every time an attribute of the element changes (in this case, it's the CSS classes being applied for the icons and their colour). I need you to screencap the stack-trace of each paused breakpoint for me, so I can see exactly where the troublesome calls are being made...

**Comment by Alhadis** [comment] 2017-08-13 04:13
Oh, and could also tell me which OS you're running, and what packages you currently have installed/active? =) You can acquire the latter by running the following command in your terminal:

~~~shell
apm ls -ib
~~~

**Comment by ashtonsix** [comment] 2017-08-13 04:46
My internet at home isn't good enough to upload screenshots quickly. I'll send details when I can access the office connection :)

**Comment by Alhadis** [comment] 2017-08-13 05:02
Alright, then. FYI, the most pertinent info is the call stack, lower-left corner:

<img src="https://user-images.githubusercontent.com/2346707/29246298-594e2e42-8038-11e7-917a-877c24976056.png" width="562" alt="Figure 2" />

**Comment by Alhadis** [comment] 2017-08-13 05:02
I'm actually surprised there's no easy way to copy the stack-trace from a paused breakpoint... although there might be in a less obvious place where I haven't looked...

**Comment by ashtonsix** [comment] 2017-08-13 11:13
You can enter `new Error().stack` in the console or right-click an entry in the call stack (the copied string is formatted badly this way though).

**Comment by Alhadis** [comment] 2017-08-13 11:53
Haha, yes, I'm aware of that. ^^ That's kinda what I was referring to when I said "no easy way".

For Node and Electron, the `Error` class also exposes the `getRawStack()`method, which allows access to V8's captured internals:

<img src="https://user-images.githubusercontent.com/2346707/29249381-b3851306-8071-11e7-84c4-64fa7151951b.png" width="434" alt="Figure 3" />

This is what I use in [`Atom-Mocha`'s default HTML reporter](https://github.com/Alhadis/Atom-Mocha/blob/8352fc7cd12d8a5b385462713249f419949f9e01/lib/reporter.js#L536-L617) for generating neatly-formatted stack traces. Gotta love V8.

**Comment by ashtonsix** [comment] 2017-08-13 13:19
`apm ls -ib`:

```
busy-signal@1.4.3
docblockr@0.11.0
file-icons@2.1.10
git-plus@7.9.3
intentions@1.1.5
language-babel@2.69.0
linter@2.2.0
linter-eslint@8.2.1
linter-stylelint@4.0.1
linter-tidy@2.3.1
linter-ui-default@1.6.3
merge-conflicts@1.4.5
minimap@4.29.3
prettier-atom@0.37.0
sequential-number@0.5.0
stylefmt@5.0.1
```

`apm -v`

```
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.1.windows.1
visual studio 2015
```

`winver`

![windows](https://user-images.githubusercontent.com/6740947/29249963-063d1e9e-8032-11e7-98f2-a2314b76f45b.PNG)

**Initial Conditions**

Both icons are gears, clicked on `.gitignore`.

**Screenshot at every breakpoint**

![1](https://user-images.githubusercontent.com/6740947/29249975-2d2b3bb2-8032-11e7-8445-6c8b918bb538.PNG)
![2](https://user-images.githubusercontent.com/6740947/29249977-2d33e6ae-8032-11e7-8a11-944a5b195325.PNG)
![3](https://user-images.githubusercontent.com/6740947/29249976-2d32b996-8032-11e7-8c35-b6349f9fb2a7.PNG)
![4](https://user-images.githubusercontent.com/6740947/29249978-2d35686c-8032-11e7-9350-125a867f0830.PNG)

**Screenshots of error thrown afterwards**

![e](https://user-images.githubusercontent.com/6740947/29249985-51c032b6-8032-11e7-80ce-73e872dbab78.PNG)
![s1](https://user-images.githubusercontent.com/6740947/29249986-51cffca0-8032-11e7-8262-acb9b99bd702.PNG)
![s2](https://user-images.githubusercontent.com/6740947/29249987-51d0dd50-8032-11e7-9fe7-f24edeb46c50.PNG)

**Comment by Alhadis** [comment] 2017-08-13 17:32
Hi @ashtonsix,

I'm sorry about the delay. I meant to get this finished last night, but instead spent the last few hours reading heart-wrenching, threatening e-mails that ripped open scars from a failed relationship that never healed (actually, it's that same depression that started my involvement with this package... trying to forget and all). Wrought with suggestions of suicide, yeah, alt that cool stuff. 👍 

I'm sure whoever is out there trying to screw my life up and Linda's life up is monitoring our activities right now so... since you're not replying from your cowardly mailinator account (`a@mailinator.com`), I'll just tell you now: I know what you're doing, and as worried for Linda as I am, I won't be goaded into contacting her again when she told me DOZENS OF TIMES over the years I'm the last person she wants to speak to.

Fuck off and leave us alone.

**Comment by Alhadis** [comment] 2017-08-13 17:33
.... okay, now... I can guarantee that's the last response anybody expected to hear...

@ashtonsix, I'll get back to you on this. Sorry, malicious anonymous stalkers + GitHub = not a good mix...

**Comment by ashtonsix** [comment] 2017-08-13 18:03
If @Alhadis's/Linda's stalker is reading this I strongly recommend [betterhelp.com](https://www.betterhelp.com/), it really helped me deal with anxiety & start mending relationships with people around me. I'm confident you're in a bad mental place right now & want to get somewhere better. If you think you're in love with @Alhadis and/or Linda I also recommend reading "Attached" by Amir Levine.

Of course, I'm not a mental health professional & don't know you so this advice should be treated with a grain of salt. Please don't attempt to contact me.

@Alhadis Sure thing. Let me know if you'd like more details on this.

**Comment by Alhadis** [comment] 2017-08-13 18:07
No no, this wasn't some dude who sounded obsessed. Some "self-confessed sadist with a fucked-up life" who got kicks from fucking other people's lives. He said this himself. Obvious hacker background, but since they were running everything through TOR, it could've been anybody or any number of people...

Yeah, okay, doesn't look like I'll be sleeping tonight/today :(

**Comment by Alhadis** [comment] 2017-08-13 18:08
This is all so fucked up... 😢

**Comment by ashtonsix** [comment] 2017-08-13 18:47
Lots of people have fucked up lives, & we all deal with this stuff in different ways. Some which are productive & others which cause harm to ourselves and the people around us. I empathise with both you and this guy you're dealing with, having been in both of your shoes at different points in my life.

@Alhadis I'd personally recommend deleting your recent messages and good luck with your situation but it's not something I want to get involved with.

**Comment by Alhadis** [comment] 2017-08-13 18:48
Yeah I'm sorry, literally the ONLY reason I've actually made my response public is because it's been the only channel I'm sure they're checking responses for. Every other e-mail's originated from what I'm sure is an unmonitored source...

**Comment by Alhadis** [comment] 2017-08-13 18:49
And yeah, I will., I just need to finish double-checking old accounts, deleting any details referring to my personal life, blah-blah-blah... then yeah, I'll fix this shit.

Sorry...

**Comment by Alhadis** [comment] 2017-08-13 20:18
**UPDATE:** Right. 8-year old YouTube account, deleted. 6-year old and unused Google+ account, deleted. Gmail password re-entered a total of 350-freakin' times or something. Security checkup complete, now let's get this shit down to business.

**Comment by ashtonsix** [comment] 2017-08-13 20:53
Glad to hear 👍

**Comment by Alhadis** [comment] 2017-08-13 21:21
Having troubles reproducing this on macOS. Guess I'll have to boot up VirtualBox.

/cc @HitomiTenshi FYI, that weird issue's returned. =)

**Comment by Alhadis** [comment] 2017-08-13 22:18
Can you confirm if this happens with opened projects that don't use version control?

**Comment by HitomiTenshi** [comment] 2017-08-13 22:53
@Alhadis I only have this problem when I have uncommitted git changes. It happens rarely and is random though. Sometimes I get it when I change a lot of files in various folders and then restart atom.

**Comment by HitomiTenshi** [comment] 2017-08-13 22:54
I don't know if this doesn't happen when no version control is used. Every project I have worked on uses git.

**Comment by Alhadis** [comment] 2017-08-13 23:01
Hrm, does @ashtonsix's [package-list](https://github.com/file-icons/atom/issues/638#issuecomment-322041740) kinda match the ones you're using? (If there' s nothing in common, I suppose I can rule out the possibility of packages having a bitchfight with each other).

**Comment by HitomiTenshi** [comment] 2017-08-13 23:14
no not really, the only things we have in common are:

```
busy-signal@1.4.3
file-icons@2.1.10
intentions@1.1.5
linter@2.2.0
linter-ui-default@1.6.3
minimap@4.29.3
```

I think it's a conflict with the default git diff package that comes with atom.

**Comment by Alhadis** [comment] 2017-08-13 23:18
> _"I think it's a conflict with the default git diff package that comes with atom."_

Ah, no, if it were, then I would be experiencing it too. It seems the catalyst of the issue rests with a particular permutation of package-settings...

**Comment by HitomiTenshi** [comment] 2017-08-13 23:31
I set the tree to hide VCS ignored files.

**Comment by ashtonsix** [comment] 2017-08-14 09:40
FYI Atom crashed, & I was then unable to replicate the issue (both files were stuck with gear icons). I was able to get back to an erroneous state by cutting the files out of the folder & then pasting them in simultaneously (similar to the way `git clone` might create many files).

It looks like `check` is returning the wrong icon b/c of multiple matches w/ the same priority (in response to `onDidMove`)

**Comment by Alhadis** [comment] 2017-08-15 13:09
Hey guys, I'm so sorry for the delay in getting back to this. 😞 Been finding it extremely difficult to focus with what's recently happened...

> It looks like `check` is returning the wrong icon b/c of multiple matches w/ the same priority (in response to `onDidMove`)

Ah no, it wouldn't be that. =) When two rules of an identical priority are to be tested, the one listed first in the config source takers higher priority

**Comment by ashtonsix** [comment] 2017-08-15 20:30
This issue is cute and fun - fixing it has absolutely no impact on my productivity (so don't beat yourself up).

Have you had any luck replicating it on your side?

**Comment by Alhadis** [comment] 2017-08-16 12:58
No, sorry, I haven't spent much time at the computer for the last couple days. For a change.

I noticed earlier tonight that there's been a regression with the `text-buffer` module, which I noticed while finishing off a fix for #634. Am addressing that first, then will look at this. =)

**Comment by Alhadis** [comment] 2017-08-17 01:26
@ashtonsix I spoke too soon, I'm afraid. Gonna have to punt this aside for a while. :\

**Comment by Alhadis** [comment] 2017-12-21 05:39
@ashtonsix Is this still happening? The most recent releases of Atom and `file-icons` featured some very critical fixes that (hopefully) smoothed out many inconsistencies and general weirdness with path handling and icon display. It wouldn't surprise me if the original issue you reported has since fixed itself. 😀

**Comment by Alhadis** [comment] 2019-03-17 11:29
I'm tentatively closing this because it's been impossible to reproduce, and improvements both to the package and to Atom's APIs have squelched numerous issues we had in the past. I'm hoping this is one of them.

As usual, if you encounter this behaviour again (with recent Atom versions), please speak up and let me know. 👍

**Closed by Alhadis** 2019-03-17 11:29 UTC
Labels: unconfirmed-bug
