### ISSUE TITLE
Files fail to refresh icons after deletion and recreation

### ISSUE THREAD

**Issue by benderTheCrime** [file-icons/atom#490] opened 2017-01-03 18:28 UTC
This is a weird issue, but I noticed that a file failed to automatically refresh it's icon when it was deleted and then recreated.

### Atom Version
1.12.7

### Steps to reproduce
- create a **FOLDER** called `index.js` and observe that it correctly has a folder icon.
- delete the `index.js` folder
- recreate a **FILE** called `index.js` and observe that it erroneously has a folder icon.
- clear the file-icons icon cache
- restart atom and observe that the `index.js` file correctly has a javascript file icon.

### Custom Styles
I have very few custom styles associated with my IDE, but I will add them here:
```
.name.icon,
.tab > .icon {
  &[data-name*="docker"]:before,
  &[data-name=".yarn-error.log"]:before,
  &[data-name=".yarnrc"]:before {
    color: @medium-blue;
  }
  &[data-name*=".jsonlint"]:before,
  &[data-name*="npm-debug"]:before,
  &[data-name=".nsprc"]:before {
    .fi;

    content: "\e91c";
    color: @medium-red;
    font-size: 17px;
  }
  &[data-name=".yarn-error.log"]:before,
  &[data-name=".yarnrc"]:before {
    .fi;

    content: "\ea1a";
    font-size: 16px;
  }
  &[data-name=".DS_Store"]:before {
    color: white;
    content: "💩";
    top: 1px;
  }
  &[data-name*="docker"]:before {
    .fi;

    content: "\f106";
    font-size: 18px;
  }
  &[data-name=".nycrc"]:before {
    .fi;

    content: "\e974";
    color: @light-green;
  }
}

.tab > .icon {
  &[data-name*=".jsonlint"]:before,
  &[data-name*="npm-debug"]:before,
  &[data-name=".nsprc"]:before,
  &[data-name*="docker"]:before {
    top: 3px;
  }
  &[data-name=".nycrc"]:before,
  &[data-name=".yarn-error.log"]:before,
  &[data-name=".yarnrc"]:before {
    top: 2px;
  }
  &[data-name=".DS_Store"]:before {
    top: 1px;
  }
}

.status-ignored {
  .name.icon:before {
    color: rgba(155, 159, 181, 0.6);
  }
}
```

Great plugin! Appreciate the work you're doing here. I think it's a necessary plugin. Let me know if there's anything I can do to help debug this issue further.

**Comment by Alhadis** [comment] 2017-01-04 02:29
Thanks for the kind words. ;)

I'm afraid this is tied down to atom/tree-view#966. Atom's `tree-view` doesn't dispatch any event to let other packages know when an entry has been deleted, so there's nothing to notify us when a cache has to be refreshed...

**Comment by jeyj0** [comment] 2017-01-26 22:28
Just mentioning that the same issue occurs when renaming a parent folder - all contained files are without icons.

Keep up the great work :)

**Comment by Alhadis** [comment] 2017-02-03 10:32
@jeyj0 Can you give me the steps to reproduce? Renaming a folder closes it in tree-view, and its contents have correct icons once it's opened.

**Comment by Alhadis** [comment] 2017-02-06 12:46
Okay, I've tried everything. There's really no way to fix this without introducing new problems.

Those interested in tracking the state of this issue are advised to follow [`atom/tree-view#966`](https://github.com/atom/tree-view/pull/966).

Until that's merged, there's nothing (safe) we can do. :disappointed:

**Comment by MatthieuLemoine** [comment] 2017-12-27 11:08
@Alhadis As https://github.com/atom/tree-view/pull/1049 was merged, are there any remaining obstacles to fix this issue ?

**Comment by Alhadis** [comment] 2017-12-27 11:12
@MatthieuLemoine I'm currently without a laptop with a graphical display, which means I'm unable to do anything Atom-related for a while. :(

I don't know how long I'm going to be like this, because I don't exactly have the money to afford a new MacBook.

**Comment by MatthieuLemoine** [comment] 2017-12-27 12:42
@Alhadis I'm willing to make a PR. As you tried to fix it, can you give me some leads on how it could be fixed ?

**Comment by Alhadis** [comment] 2017-12-27 12:45
It largely ties down to the `atom-fs` module, which isn't being notified of changes to the filesystem (at least, those which aren't being tracked by the package). Now that Atom has a formal API for filesystem watching, it should be much easier to achieve than what I originally planned.

**Comment by Lassi** [comment] 2018-01-06 03:05
Hey there,

I submitted a PR to fix this issue but I'm not familiar at all with the Atom ecosystem. Please let me know what you think about it!

Cool plugin by the way, thanks for all the work you've done ;)

**Closed** 2018-01-08 14:22 UTC
Labels: atom-fs, bug
