### ISSUE TITLE
JS files change their icon to the JSX icon on opening

### ISSUE THREAD

**Issue by garrettlr** [file-icons/atom#709] opened 2018-02-20 17:29 UTC
Hey,

So this might be an issue with file-icons and it might be an issue with language-babel, I'm not entirely sure. Any time I open a file ending in .JS, whether it's a basic JS file, a JS file containing JSX, or a jest test, the icon switches over to the JSX icon in both the tree view and the tab. 

Any idea what's going on?

Thanks!

**Comment by Alhadis** [comment] 2018-02-20 17:46
Dupe of #704. Reading that thread will explain what you're seeing (and that we can't do anything about it until Atom v1.24.1 is released). There's a workaround for the time being, which I've [explained here](https://github.com/file-icons/atom/issues/704#issuecomment-366134001).

Apologies for the inconvenience. :disappointed:

**Closed by Alhadis** 2018-02-20 17:46 UTC

**Comment by garrettlr** [comment] 2018-02-20 17:47
@Alhadis Sorry! I looked at the existing issues and must have missed that one. Thanks for pointing it out to me!

**Comment by Alhadis** [comment] 2018-02-20 17:53
You're welcome, mate. =)
