### ISSUE TITLE
Atom 1.24.0 odd behavior

### ISSUE THREAD

**Issue by dawnerd** [file-icons/atom#704] opened 2018-02-14 01:55 UTC
As I was opening files the icons changed back to the default JS icon. They were showing the js test icon. Is that something that's changed recently? Maybe latest atom broke something.

**Comment by JosephTLyons** [comment] 2018-02-14 03:28
Did you just upgrade to Atom 1.24.0?  I just did and now all my Elisp file icons are showing up as Lisp file icons.

**Comment by dawnerd** [comment] 2018-02-14 03:33
Yep, 1.24.0

**Comment by JosephTLyons** [comment] 2018-02-14 03:46
It seems Atom 1.24.0 broke File Icons.

**Comment by Alhadis** [comment] 2018-02-14 06:42
Nothing changed recently in this package, no. It seems there's been a regression in Atom's code. :confused:

Sigh... I'll investigate once I'm back at a computer.

**Comment by dawnerd** [comment] 2018-02-14 06:56
Some more investigation:

Disabling and re-enabling the package show the correct icons. As soon as the file is opened the icon changes back to the wrong one.

**Comment by markmarkyesyes** [comment] 2018-02-14 16:09
I am experiencing similar issues with .js files on updating to atom 1.24.0.

Icons show correctly until I open the file, then both *.js and *.spec.js files change to a blue jsx icon.

Upon uninstalling and reinstalling, the icons maintain the erroneous changes described above. previously selected files maintain a jsx icon, and unselected files have appropriate icons.

**Comment by djamesjones4** [comment] 2018-02-14 18:00
Same issue. When I open .js files the icon changes from orange JS icon to blue JSX icon. When I disable and reenable file-icon the icon remains the same. 

Using Atom v1.24.0

**Comment by Alhadis** [comment] 2018-02-15 02:57
As a temporary workaround, you can disable the grammar strategy in the `file-icons` package's settings. Unfortunately, that'll mean icons don't update when you override the editor's grammar *manually*, but so far that's the most reasonable solution.

The package relied on `atom.textEditors.getGrammarOverride` to report an empty string for anything that wasn't manually overridden, so we're kind of stuck. :confused:

**Comment by colbyy** [comment] 2018-02-16 02:54
Atom v1.24.0
file-icons v2.1.16

related issue: Atom detects all my JavaScript files as "JavaScript with JSX" and the file icons change to blue jsx even though there's no jsx. Seems like more of an Atom bug.

**Comment by Alhadis** [comment] 2018-02-16 03:17
Alright guys, this has been fixed upstream in [`atom/atom#16754`](https://github.com/atom/atom/pull/16754) and will probably land in Atom 1.24.1. Gonna close this as there's really nothing more we can do on our end. In the meantime, you can disable the grammar-strategy (as explained above). Remember to run the `file-icons:clear-cache` command on affected projects if the icons are still wrong.

> May I make a suggestion? I completely missed this package when searching for "Emacs" or "Elisp," it never showed up in searches

That's... really weird, because both `Emacs` and `Elisp` are [listed as keywords](https://github.com/Alhadis/language-emacs-lisp/blob/def2b3e032a9a256211918f6afdd88d69943078f/package.json#L5). :confused: Really can't explain that one, sorry. :disappointed:

## For those curious about what was going on
The package's config file defines a [`scope`](https://github.com/file-icons/atom/blob/1f3330d8962b4a7b0dafb8023f32d3964d165298/config.cson#L47-L50) property which is matched against a grammar's `scopeName` property when a user overrides the grammar of a file. Currently, only one icon can be mapped to a scope (a known limitation I hope to fix in future).

**Closed by Alhadis** 2018-02-16 03:17 UTC

**Comment by JosephTLyons** [comment] 2018-02-17 03:11
Weird.  I didn't do anything (as in I didn't implement the workaround you mentioned) and my file icons are now correct.  I did nothing since it was broken by Atom 1.24.0 and all-of-the-sudden, they came back and are working as expected.

**Comment by Alhadis** [comment] 2018-02-17 06:16
@JosephTLyons Are you referring to your Elisp files now showing the usual Emacs icon?

If so, that'll be because you installed the `language-emacs-lisp` package. ;) It takes precedence over `language-lisp` due to alphabetical order - had the latter been named `atom-lisp-support`, well, you'd still be seeing the wrong icon.

That was how I knew you didn't have my Elisp package installed 😉 (and partly also why I recommended it).

**Comment by JosephTLyons** [comment] 2018-02-17 06:34
@Alhadis , jeez.  You are correct.  I disabled `language-lisp` when I downloaded `language-emacs-lisp`.  I already forgot about this.  Sorry for this, brain is fried from classes.

**Comment by Alhadis** [comment] 2018-02-17 06:50
> fried from classes.

Less Java, more Lisp. 😆

**Comment by Alhadis** [comment] 2018-02-21 00:13
Guys, once I finish repairing the package's test-suite, I'm gonna roll a patch release that disables the grammar-strategy automatically for Atom 1.24.0 users (and **only** that version). I've closed the fourth duplicate report just now, and I shudder to think how many people are getting confused by this who *aren't* checking GitHub to see what's going on.

Which means that after you download/install the next `file-icons` release, you can safely re-enable the grammar strategy since the package will re-enable it for you once the next Atom release is shipped. It's already been included in [`v1.25.0-beta1`](https://github.com/atom/atom/releases/tag/v1.25.0-beta1).

**Comment by JosephTLyons** [comment] 2018-02-21 01:08
@Alhadis , sounds excellent!  Thank you for going the extra mile to automate that process for others.  Any sort of ballpark ETA for this?

BTW, I read your style guidelines, just for fun, and enjoyed the humor sprinkled throughout.

**Comment by Alhadis** [comment] 2018-02-21 01:48
> Any sort of ballpark ETA for this?

Well the package specs are about 80-90% repaired. Probably in the next couple of days, I assume. :)

> BTW, I read your style guidelines, just for fun,

Haha, thank you. :wink: It was lighthearted because I wrote it while high on energy drinks. Make no mistake though, the underlying message is dead serious.

**Comment by Alhadis** [comment] 2018-02-21 01:51
Everybody here should also [gloss through them](https://raw.githubusercontent.com/Alhadis/Coding-Style/master/README.md) and admire my ~~fucked-up OCD~~ uncanny ability to wrap paragraphs at 80 columns *exactly* without hyphenating or padding any sentences.

If anybody has noticed the way I line-wrap every fucking Git commit message I write too, this should be no surprise.

(Yes, I know I probably look mental. Rest assured, I've just had too much practice and now it's second nature to me...)

**Comment by JosephTLyons** [comment] 2018-02-21 01:54
@Alhadis , absolutely.  No I could %100 tell from your tone that you meant business about your particular style, but I also enjoyed how it was written.

**Comment by JosephTLyons** [comment] 2018-02-21 02:19
Also, I'm a bit blown away by the perfectly consistent use of 80 columns with no padding.  I'm not even sure how that could work for every sentence without doing some sort of additional tweaks on words and such, but somehow, you have seem to have pulled it off.  Looks very clean.

**Comment by Alhadis** [comment] 2018-02-22 00:26
Did you remember to clear your cached paths?

If not, that'll be handled automatically too. I've [bumped](https://github.com/file-icons/atom/commit/5377c8c044d615f88b88dc3b52c28da187d9bfab#diff-340e5d07b38ee06f6a31fb9ae9a5fe27) the internal version counter in the `Storage` class, which will cause all caches to be flushed upon the next install.

**Comment by JosephTLyons** [comment] 2018-02-22 18:55
I downloaded the newest update and reenabled the grammar option and all seems to be working correctly.  Files are displaying correctly no matter which way I set the setting.  Very nice work and appreciate the fast fix.
