### ISSUE TITLE
JSX misidentified

### ISSUE THREAD

**Issue by TrueWill** [file-icons/atom#706] opened 2018-02-17 17:22 UTC
file-icons 2.1.16, Atom 1.24.0, Mac OS

- some Jest tests identified as JSX (despite no JSX)
- some utility .js files (just functions, no JSX) identified as JSX
- .js file of constants (action types) identified as JSX
- multiple React components not identified as JSX (show as JS)
- when click on React component file in tree, changes from JS to JSX

**Comment by Alhadis** [comment] 2018-02-17 17:36
Duplicate of #704, caused by a regression introduced in Atom v1.24.0. Already fixed upstream, nothing we can do on our end but wait for the next patch.

More details: https://github.com/file-icons/atom/issues/704#issuecomment-366134001

**Closed by Alhadis** 2018-02-17 17:36 UTC
