### ISSUE TITLE
Icons change once I click on it

### ISSUE THREAD

**Issue by PierreMarchand20** [file-icons/atom#707] opened 2018-02-18 14:31 UTC
I assume that `.cpp` files are blue and `.hpp` files are purple (more or less). I recently noticed that when I click on a `.hpp` file, the icon turns blue like the `.cpp` files ,and it stays like that: here I clicked on `specialfct.hpp` but not on `refsolf.hpp`
![capture d ecran 2018-02-18 a 15 28 15](https://user-images.githubusercontent.com/15056323/36352975-9641a154-14c0-11e8-9fe9-a062f617b63a.png)

May be related to #638 ?

**Comment by Alhadis** [comment] 2018-02-18 14:49
Duplicate of #704, caused by a regression introduced in Atom v1.24.0. Already fixed upstream, nothing we can do on our end but wait for the next patch.

More details: https://github.com/file-icons/atom/issues/704#issuecomment-366134001

**Comment by Alhadis** [comment] 2018-02-18 14:49
@PierreMarchand20 If the problem persists after you disable the grammar strategy (and clear the icon-cache), then yes, it's possibly connected to the issue you've linked to.

**Closed by Alhadis** 2018-02-18 14:49 UTC

**Comment by PierreMarchand20** [comment] 2018-02-19 08:49
Disabling the grammar startegy works, thank you !
