### ISSUE TITLE
Conflict with tree-view-autoresize package

### ISSUE THREAD

**Issue by ooJerryLeeoo** [file-icons/atom#580] opened 2017-04-05 00:01 UTC
Problem as the title, here's an example:

Before disable `file-icons`:

![2017-04-05 07_59_28](https://cloud.githubusercontent.com/assets/20783502/24684076/05a7e24c-19d6-11e7-8e63-85468c274948.gif)

After disable `file-icons`:

![2017-04-05 08_00_29](https://cloud.githubusercontent.com/assets/20783502/24684084/0cf21040-19d6-11e7-80f6-a0e1bce91f2d.gif)

**Comment by Alhadis** [comment] 2017-04-05 01:53
I don't understand what the problem is.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 01:56
In the gif-1 you can see I close tree-view before I close atom, but after I open atom, the tree-view show up again.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 01:59
It should be closed when I restart atom.

**Comment by Alhadis** [comment] 2017-04-05 02:59
Ah, I see.

Run this in your dev console:

~~~js
atom.config.set("file-icons.revealTreeView", false);
~~~

Then restart. Better?

**Comment by ooJerryLeeoo** [comment] 2017-04-05 04:25
@Alhadis Thank you :kissing_heart: , It's now work very well for me now :tada:

**Comment by Alhadis** [comment] 2017-04-05 05:36
My pleasure!

I'll update the readme's troubleshooting section to include this, because you're not the first person to bring this up.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 05:40
@Alhadis But there is an new [problem](https://github.com/lexcast/tree-view-autoresize/issues/12) spawn when run `atom.config.set("file-icons.reavelTreeView", fales);` I post on the other packages call `tree-view-autoresize`, can you look at it ? maybe you can fix it.

**Comment by Alhadis** [comment] 2017-04-05 06:04
I'll look once I'm in front of a desktop computer again.

**Comment by Alhadis** [comment] 2017-04-05 08:38
@ooJerryLeeoo Does this still happen after disabling the `tree-view-autoresize` package?

**Comment by ooJerryLeeoo** [comment] 2017-04-05 10:19
@Alhadis `tree-view-autoresize` is a package that while auto adjust the `tree-view` width when you expand folder, so my problem here is that after disable `revealTreeView`, the `tree-view-autoresize` package cannot auto adjust the `tree-view` width.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 10:21
@Alhadis If you still don't understand what I'm saying here's a gif to reproduce the :bug::

![2017-04-05 18_19_10](https://cloud.githubusercontent.com/assets/20783502/24701320/8f768798-1a2c-11e7-8f90-ef1e12960568.gif)

**Comment by Alhadis** [comment] 2017-04-05 10:21
I'm not asking you to disable `tree-view-autoresize` permanently. Just disable it once, and restart Atom. I want to be 100% sure there's nothing else that's causing problems here.

Once confirmed, you can re-enable the package again. Then I'll work on a fix.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 10:32
@Alhadis I've found the problem 😄 
The problem here is that the `tree-view-autoresize` will not start running after restart atom, because after I disable and enable the package, the `tree-view` will start autoresize again.

![2017-04-05 18_31_41](https://cloud.githubusercontent.com/assets/20783502/24701723/22e0a044-1a2e-11e7-983e-6a286bf53a09.gif)

**Comment by Alhadis** [comment] 2017-04-05 10:39
I'm sorry, I'm still confused... :( I feel there's a language barrier here.

Anyway, I'll just assume you don't have any other packages installed which are causing complications. I see the error in my console, so I'll work on fixing that, I guess.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 11:03
@Alhadis Sorry, my english is terrible.

Okay, I will try to explain this issue as well as I can.
Here's how the `tree-view-autoresize` work before I run `atom.config.set("file-icons.revealTreeView", false);`

![2017-04-05 18_56_10](https://cloud.githubusercontent.com/assets/20783502/24702498/8f22ceb4-1a31-11e7-9e51-938d966c5794.gif)

and my problem is after I run `atom.config.set("file-icons.revealTreeView", false);` and restart Atom, the `tree-view-autoresize` not working anymore, until I re-enable the `tree-view-autoresize` package.

![2017-04-05 18_59_44](https://cloud.githubusercontent.com/assets/20783502/24702625/27244940-1a32-11e7-802c-3876db440f49.gif)

**Comment by Alhadis** [comment] 2017-04-05 14:44
@ooJerryLeeoo Don't worry. =) I understand that English isn't your first language, so you don't have to apologise.

I'm having troubles reproducing this, even when following your steps. Could you please do the following for me?

1. Copy+paste the contents of `~/.atom/config.cson` for me... I need to see what your package settings are.
2. Run the following command in your Terminal: `apm ls -i`. Copy+paste its output - this shows us what packages and themes are installed and active.

**Comment by ooJerryLeeoo** [comment] 2017-04-05 14:46
@Alhadis Okay, [here's](https://github.com/ooJerryLeeoo/dot-atom) my config repository.

**Comment by Alhadis** [comment] 2017-04-05 14:46
谢谢！That's perfect, thank you. =)

**Comment by ooJerryLeeoo** [comment] 2017-04-05 14:49
By the way, that's simplified chinese, I'm using traditional chinese :smile:

**Comment by Alhadis** [comment] 2017-04-05 14:51
Oh whoops, I noticed you're from Taiwan. Haha, sorry... I must've confused you with [another recent reporter](https://github.com/file-icons/atom/issues/578) who's from Beijing.

By the way, does this error still happen when you start Atom in dev-mode?

**Comment by ooJerryLeeoo** [comment] 2017-04-05 14:56
@Alhadis Yes, it still happen when dev-mode.

And I've found another new problem: I cannot scroll past end after run `atom.config.set("file-icons.revealTreeView", false);`

**Comment by Alhadis** [comment] 2017-04-05 14:58
Are errors being emitted to your dev-console?

Also, does the error happen when you deactivate EVERY package EXCEPT for `file-icons` and `tree-view-autoresize`? I noticed there's quite a few things installed... sometimes one package does something that causes another package to behave badly. So it might be the fault of some third package...

**Comment by ooJerryLeeoo** [comment] 2017-04-05 15:23
@Alhadis I get this console message `~/.atom/packages/file-icons/lib/consumers/tree-view.js:38 Uncaught (in promise) TypeError: Cannot read property '0' of null(…)`

and, It still happened when I disable all package except `file-icons` and `tree-view-autoresize`...

**Comment by Alhadis** [comment] 2017-04-05 16:24
I was writing a reply when a wolf spider decided to crawl across my keyboard... and after catching it and releasing it outside, I returned to find my message gone. :\ Guess the spider snuck in to eat what I was typing.

Anyway, it was something along the lines of asking you to check if [this is what you see](https://cloud.githubusercontent.com/assets/2346707/24715697/c46aecbc-1a6f-11e7-9105-e70600bce945.png) when you enter `_FileIcons.treeView` in the dev-console, but it doesn't matter. I managed to get the full stack trace:

~~~
Uncaught (in promise) TypeError: Cannot read property '0' of null(…) @ tree-view.js:38
    activate                                                         @ tree-view.js:38
    updateStatus                                                     @ consumer.js:206
    disposables.add.atom.packages.onDidActivatePackage               @ consumer.js:84
    module.exports.Emitter.simpleDispatch                            @ emitter.js:25
    module.exports.Emitter.emit                                      @ emitter.js:129
    (anonymous function)                                             @ package-manager.coffee:469
~~~

... and with a little editing, I noticed `treeView` really is `null` when it shouldn't be `null`...
<img src="https://cloud.githubusercontent.com/assets/2346707/24715661/9e8a0b54-1a6f-11e7-8419-6238044f318a.png" width="680" alt="Figure 2" />

So far, zero luck! I'm probably going to kludge this one, and pray to God that @50Wliu accidentally slips, falls and presses the **Merge** button on atom/tree-view#1009. 😁

**Comment by ooJerryLeeoo** [comment] 2017-04-05 16:42
@Alhadis Here's what I get when I run `_FileIcons.treeView` in the dev console:

![screen shot 2017-04-06 at 00 40 26](https://cloud.githubusercontent.com/assets/20783502/24716514/dd7b890e-1a61-11e7-97d7-b2e9f2f5a056.png)

**Comment by Alhadis** [comment] 2017-04-05 16:49
Wait, you're using Atom Beta? Okay, this changes everything.

When filing a bug report, **please** make sure to include all possible version information. Maintainers prefer to have too much information instead of not enough.

I'll have to recheck everything using Beta... **sigh** :(

**Comment by Alhadis** [comment] 2017-04-05 17:23
@ooJerryLeeoo I've [pushed a fix for this](https://github.com/file-icons/atom/commit/0f0bbc828abb840a32853a1fceb87afb1aba6074), but I need you to tell me it really works.

Could you please clone the latest changes to `file-icons` locally? Run this in your terminal:

~~~shell
cd ~/.atom/dev/packages
git clone https://github.com/file-icons/atom.git file-icons && cd file-icons
apm install .
~~~

Then restart Atom and tell me if the error vanishes.

**Comment by ooJerryLeeoo** [comment] 2017-04-06 01:14
It fixed :tada: very thanks :fist_oncoming:

**Comment by Alhadis** [comment] 2017-04-06 01:19
<img src="https://cloud.githubusercontent.com/assets/2346707/24733413/d804673a-1aba-11e7-8194-155240af7457.png" alt="" />

Thank **fuck** for that. 😀  Thank you so much for your patience and help with all of this.

**Closed by Alhadis** 2017-04-06 01:19 UTC
Labels: bug

**Comment by ooJerryLeeoo** [comment] 2017-04-10 01:49
So... you gonna push a new release for this, right?
