### ISSUE TITLE
Solidity icon shows up correctly in tree view, but not in the tab

### ISSUE THREAD

**Issue by aenhsaihan** [file-icons/atom#713] opened 2018-03-02 07:46 UTC
I tried restarting Atom as well as removing and adding my project, but I still end up with the same issue.

<img width="1280" alt="screen shot 2018-03-02 at 2 41 58 am" src="https://user-images.githubusercontent.com/4359103/36888537-e342e43e-1dc3-11e8-8fb6-943e0bbe22ed.png">

**Comment by Alhadis** [comment] 2018-03-02 08:01
Duplicate of #708. See the comments at the end of the thread.

Short answer: Uninstall `language-etherium`.

**Closed by Alhadis** 2018-03-02 08:01 UTC
