### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MauroNavaLuevanos** [file-icons/atom#575] opened 2017-03-27 23:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.1

### Stack Trace

Failed to activate the file-icons package

```
At Cannot read property 'onDidChangeIcon' of undefined

TypeError: Cannot read property 'onDidChangeIcon' of undefined
    at /packages/file-icons/lib/service/icon-node.js:30:12)
    at /packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/packages/file-icons/lib/consumers/tree-view.js:82:25)
    at TreeView.rebuild (/packages/file-icons/lib/consumers/tree-view.js:73:9)
    at TreeView.activate (/packages/file-icons/lib/consumers/tree-view.js:54:8)
    at TreeView.updateStatus (/packages/file-icons/lib/consumers/consumer.js:206:9)
    at TreeView.init (/packages/file-icons/lib/consumers/tree-view.js:30:8)
    at ConsumerManager.init (/packages/file-icons/lib/consumers/all.js:33:13)
    at Object.activate (/packages/file-icons/lib/main.js:17:13)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
 10x -5:05.2.0 core:backspace (input.hidden-input)
  5x -5:00.8.0 core:delete (input.hidden-input)
     -4:57.7.0 core:backspace (input.hidden-input)
     -4:54.6.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  9x -4:53.4.0 core:backspace (input.hidden-input)
  5x -4:51.1.0 core:delete (input.hidden-input)
  2x -4:49.2.0 core:backspace (input.hidden-input)
     -4:43.4.0 autocomplete-plus:confirm (input.hidden-input)
  2x -4:41.3.0 core:backspace (input.hidden-input)
     -4:40.3.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -4:31.7.0 core:undo (input.hidden-input)
  4x -4:28.7.0 core:backspace (input.hidden-input)
     -4:22.5.0 autocomplete-plus:confirm (input.hidden-input)
     -4:21.4.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  3x -4:11.1.0 core:backspace (input.hidden-input)
  3x -1:58.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.use-animations.paint-cursor.theme-atom-material-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
emmet 2.4.3 
file-icons 2.1.1 
pigments 0.39.1 
```

**Comment by Alhadis** [comment] 2017-03-30 08:23
Duplicate of #568.

**Closed by Alhadis** 2017-03-30 08:23 UTC
