### ISSUE TITLE
Icon error when file name as  same as folder.

### ISSUE THREAD

**Issue by godtail** [file-icons/atom#564] opened 2017-03-21 03:34 UTC
I create a folder name `setting.php` (mistake),  then i delete it and create the same name file `setting.php`,  but the icon still folder's.

![image](https://cloud.githubusercontent.com/assets/18417644/24131553/4a009784-0e2a-11e7-9545-375a99a58295.png)

**Comment by Alhadis** [comment] 2017-03-21 03:35
Duplicate of #490, which I can't fix until the Atom team merges [`atom/tree-view#966`](https://github.com/atom/tree-view/pull/966).

**Closed by Alhadis** 2017-03-21 03:35 UTC
