### ISSUE TITLE
Uncaught Error: Cannot find module '~/AppData\Local\atom\app-1.17.0-beta3\resources\app\node_modu...

### ISSUE THREAD

**Issue by Stanzilla** [file-icons/atom#591] opened 2017-04-25 00:27 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta3 x64
**Electron**: 1.3.14
**OS**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.3

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Benjamin\AppData\Local\atom\app-1.17.0-beta3\resources\app\node_modules\tabs\lib\util.js'

```
At C:\Users\Benjamin\AppData\Local\atom\app-1.17.0-beta3\resources\app\static\<embedded>:1

Error: Cannot find module 'C:\Users\Benjamin\AppData\Local\atom\app-1.17.0-beta3\resources\app\node_modules\tabs\lib\util.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:66:1)
    at Tabs.loadPackageFile (/packages/file-icons/lib/consumers/consumer.js:231:10)
    at Tabs.activate (/packages/file-icons/lib/consumers/tabs.js:50:22)
    at Tabs.updateStatus (/packages/file-icons/lib/consumers/consumer.js:206:9)
    at Immediate.setImmediate (/packages/file-icons/lib/consumers/consumer.js:82:27)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
 48x -5:59.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -0:14.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-vivid-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-increment 0.3.4 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
auto-detect-indentation 1.3.0 
autocomplete-html-entities 0.1.0 
autocomplete-php 0.3.7 
busy-signal 1.4.0 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.3 
file-watcher 1.1.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-batch 0.4.0 
language-blade 0.29.0 
language-cmake 0.3.0 
language-dots 0.0.4 
language-lua 0.9.11 
language-lua-wow 0.2.0 
language-powershell 4.0.0 
language-toc-wow 0.2.0 
less-than-slash 0.16.0 
linter 2.1.4 
linter-luacheck 1.2.0 
linter-php 1.3.2 
linter-ui-default 1.2.3 
MagicPython 1.0.9 
markdown-scroll-sync 2.1.2 
minimap 4.27.1 
one-dark-vivid-syntax 1.7.1 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-base 2.1.11 
php-integrator-navigation 1.1.2 
php-integrator-tooltips 1.1.5 
pigments 0.39.1 
pretty-json 1.6.3 
project-plus 0.9.0 
revert-buffer 0.5.0 
sort-lines 0.14.0 
space-tab 0.4.2 
sync-settings 0.8.1 
synced-sidebar 0.4.3 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
trailing-spaces 0.4.0 
```

**Comment by Alhadis** [comment] 2017-04-25 06:28
Dupe of #590, which is already fixed and staged for release.

**Closed by Alhadis** 2017-04-25 06:28 UTC
