### ISSUE TITLE
Improve the startup time

### ISSUE THREAD

**Issue by mittalyashu** [file-icons/atom#674] opened 2017-11-19 13:55 UTC
![image](https://user-images.githubusercontent.com/29014463/32991328-5eb4d484-cd5f-11e7-87e1-33a53f56f5d5.png)

**Comment by Alhadis** [comment] 2017-11-19 13:56
Duplicate of file-icons/atom#674, which is thankfully due to be fixed in the near future.

**Closed by Alhadis** 2017-11-19 13:56 UTC
