### ISSUE TITLE
Tree view not showing at all when adding a project folder

### ISSUE THREAD

**Issue by Tms157** [file-icons/atom#496] opened 2017-01-04 09:49 UTC
Also a new bug i think thats been caused by the last update when you open a project folder it does not open the tree view at all now you cart see the folder you just added like this: http://imgur.com/a/7ioL4 with the plugin disabled its like this: http://imgur.com/a/VYM00 if i connect to my server the tree view then shows up again (No icons tho). This just started happening after i updated.

Edit: Also seems to give 'issue #433' when connecting with remote-ftp but seems to still allow me to connect not sure what that means but it does not do it when file-icons is disabled.

**Comment by Alhadis** [comment] 2017-01-04 10:00
Dupe of #494, and should be fixed in the latest patch.

**Closed** 2017-01-04 10:00 UTC

**Comment by Tms157** [comment] 2017-01-04 10:02
This is on the newest patch, i dint have this problem till today when i installed 2.0.6

**Comment by Alhadis** [comment] 2017-01-04 10:02
I just cut another one. v2.0.7

**Comment by Tms157** [comment] 2017-01-04 10:03
ahhhh, my bad thanks for fast response tho!
