### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by jaberson** [file-icons/atom#521] opened 2017-01-17 07:18 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /Users/jiaxiongsheng/.atom/packages/file-icons/lib/service/strategy-manager.js:82

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at StrategyManager.query (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/service/strategy-manager.js:82:25)
    at IconDelegate.getCurrentIcon (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/service/icon-delegate.js:167:20)
    at new IconNode (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/service/icon-node.js:43:20)
    at new TreeEntry (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/consumers/tree-entry.js:41:19)
    at TreeView.track (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/consumers/tree-view.js:72:25)
    at TreeView.rebuild (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/consumers/tree-view.js:63:9)
    at disposables.add.atom.project.onDidChangePaths (/Users/jiaxiongsheng/.atom/packages/file-icons/lib/consumers/tree-view.js:47:45)
    at Function.module.exports.Emitter.simpleDispatch (/Users/jiaxiongsheng/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/jiaxiongsheng/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/Users/jiaxiongsheng/Desktop/Atom.app/Contents/Resources/app.asar/src/project.js:270:29)
    at /Users/jiaxiongsheng/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1024:40
    at EventEmitter.<anonymous> (/Users/jiaxiongsheng/Desktop/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -0:46.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sync-settings"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
atom-clock, v0.1.3 (active)
atom-html-preview, v0.1.22 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.9 (active)
git-control, v0.8.2 (active)
language-vue, v0.21.1 (active)
sync-settings, v0.8.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jaberson** [comment] 2017-01-17 07:19
ll

**Comment by Alhadis** [comment] 2017-01-17 07:20
Dupe of #519, in the process of being fixed.

**Closed by Alhadis** 2017-01-17 07:20 UTC
Labels: duplicate
