### ISSUE TITLE
Icons not showing with remote-ftp

### ISSUE THREAD

**Issue by Tms157** [file-icons/atom#486] opened 2017-01-03 12:21 UTC
Hello,

Im useing remote-ftp and the icons are no longer working it was fine before christmas. Screenshot: http://imgur.com/a/ox4s4

**Comment by awrico** [comment] 2017-01-03 22:38
Hi,

I confirm and here are my few words: loading project to the same window causes that the icons in tree-view 'disappear'. After invoking 'file-icons:clear-cache' command and restarting Atom (or reloading window) icons in tree-view appear again but... till next project loading.

**Comment by Alhadis** [comment] 2017-01-04 02:37
Does this still happen after installing `file-icons` v2.0.5?

**Comment by dxiaogang** [comment] 2017-01-04 03:36
same issue, it's not working in Nuclide's file-tree,v2.0.5

**Comment by Alhadis** [comment] 2017-01-04 09:00
@dxiaogang Nuclide's file-tree is a separate issue, please see facebook/nuclide#951 for details.

**Comment by awrico** [comment] 2017-01-04 09:06
After installing file-icons 2.0.6 the problem seems to be fixed. Thanks.

**Comment by richarddewit** [comment] 2017-01-04 09:19
Duplicate of #480

**Comment by Tms157** [comment] 2017-01-04 09:32
After installing 2.0.6 its still not working with remote-ftp

**Comment by Alhadis** [comment] 2017-01-04 09:37
Ah, they must be using their own tree-view thing like Nuclide is doing.

This will involve sending them a pull request to use the icon-service then...

**Comment by Alhadis** [comment] 2017-01-10 02:12
@Tms157 / @NoMad42 I've prepared a fix for this issue, can you tell me if it works?

```bash
cd /tmp
git clone https://github.com/Alhadis/remote-ftp && cd remote-ftp
git checkout file-icons
apm install . && apm link -d .
```

Then restart Atom in development mode.

**Comment by Alhadis** [comment] 2017-01-11 03:37
Never mind, I remembered that [public FTP exists](ftp://ftp.astron.com/).

**Comment by Tms157** [comment] 2017-01-11 09:05
Hello, i could not get this to work in dev mode wither.

**Comment by Tms157** [comment] 2017-01-11 09:11
Not sure if this helps at all? http://imgur.com/a/L2y0Q i may have just done it wrong im not sure haha

**Comment by Alhadis** [comment] 2017-01-11 09:13
That's actually not even related. :p Don't worry, I have it working. I just wasn't able to get onto an FTP connection until recently. Thanks. :)

**Comment by Tms157** [comment] 2017-01-11 10:20
Any ETA on an update? I miss the beautiful icons :)

**Comment by Alhadis** [comment] 2017-01-11 10:21
I'll have a pull request ready in the next couple of days, but it really all comes down to how soon the package's maintainer will get around to merging it...

**Comment by Tms157** [comment] 2017-01-11 10:30
Ah ok no worrys

**Comment by Alhadis** [comment] 2017-01-19 18:29
Since this is now an upstream issue, I'm closing this. There's nothing left to do on our end.

Those interested in tracking the state of this should refer to mgrenier/remote-ftp#639.

**Closed by Alhadis** 2017-01-19 18:29 UTC
